//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SingleGear
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bike
    {
        public int BikeId { get; set; }
        public string FrameColour { get; set; }
        public string SaddleColour { get; set; }
        public string HandlebarColour { get; set; }
        public string WheelsColour { get; set; }
        public Nullable<int> UserId { get; set; }
    }
}
